title: Third Coast
description: Stryke Force 2767 Third Coast swerve drive, talon configuration and telemetry API for FRC robots
show_downloads: false
google_analytics: UA-108186367-1
theme: jekyll-theme-minimal
